### ISSUE TITLE
질문/각주 팝업, 네비게이션 바 활성화

### ISSUE THREAD

**Issue by surplus-dev** [wkpark/moniwiki-theme-bootstrap3#1]
이 두개를 활성화 하려면 어떻개 해야하나요?

**Comment by surplus-dev** [comment]
[리그베다](http://bbs.rigvedawiki.net/index.php?mid=chinwag&document_srl=92240&rnd=92341#comment_92341)

**Comment by raygerious1234** [comment]
ㅇㅇ
