### ISSUE TITLE
스크롤 버튼 글꼴 로딩 안됨

### ISSUE THREAD

**Issue by NbverHub** [wkpark/moniwiki-theme-bootstrap3#2]
1. folding 매크로 css가 없음
2. 우측 하단 버튼들이 고정되지 않고 이미지도 뜨지 않음
3. 표 캡션이 원래 자동으로 중앙정렬되었는데 정렬되지 않음
4. 일부 테마 옵션 미작동

**Comment by wkpark** [comment]
2번은 우측 하단 버튼이 뭐죠? 우측 상단에는 위키 아이콘 등등이 있습니다만

4번 일부 테마 옵션은 무얼 말씀하시는지요? paper테마를 그대로 가져와서 고친 것이라 예전의 옵션은 아예 작동하지 않을 수 있습니다.

**Comment by NbverHub** [comment]
1. scroll-buttons 들이요. 랜덤, 편집, 상하단 스크롤 버튼..
2. theme.php에 있는 옵션 중 일부가 활성화해도 작동하지 않더군요.

**Comment by NbverHub** [comment]
추가로 edge에서는 아래 smiley 버튼들이 그대로 최근변경까지 칸을 벗어나고, 크롬에서는 일부 이모티콘이 잘리네요.

**Comment by wkpark** [comment]
1. 아 넵. 확인했습니다. 스크롤 버튼의 경우에는 font awsome을 사용해서 그렇습니다.
   기본 부트스트랩의 glyphicon을 쓰게끔 고쳤습니다.

---

fontawesome을 사용하려 하시는 경우라면,
1. fontawsome 글꼴을 로딩함.
2. `$_srollbuttons_font='fa';` 옵션 세팅.

---

fontawesome을 로딩하려면, 두가지 방식이 있는데, 1) 테마 자체의 `$_load_fa` 옵션을 켜거나, 2) config.php에서 직접 로딩.

`$_load_fa=1`; 이라고 theme.php 혹은 local.php에서 정의 혹은

config.php에 넣는 경우에는 `$metatags`에 다음과 같은 줄을 추가해주시면 됩니다.

```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.css" />
```

**Comment by wkpark** [comment]
기타 여기에 올려주신 1번, 3번 이슈는 알고 있는 내용이므로 닫습니다.

작동하지 않는 옵션은 이미 모두 지웠더군요. 나머지 옵션들은 작동해야 정상입니다.
일부 옵션은 옵션들끼리 의존성이 있고요.

`$_use_qr` 혹은 `$_use_editstat` 등의 옵션은 사이드바를 켜야 작동합니다.
