### ISSUE TITLE
메뉴바 로고 및 우측 메뉴 고정 지원

### ISSUE THREAD

**Issue by NbverHub** [wkpark/moniwiki-theme-bootstrap3#3]
1. 사이드바 옵션을 켰을 경우 PC에서 스크롤하면 사이드바 메뉴가 따라서 내려오게 하는 옵션이 있으면 좋을 것 같습니다.
2. use default navbar 옵션을 키면 좌측에 공란이 생기는데, 위키명이나 로고가 있어야할 공간으로 추측되는데 어쩐지 아무것도 뜨지 않네요.

**Comment by wkpark** [comment]
2번 로고 파일을 집어넣지 않았었네요.
아예 기본에서 로고를 빼고 `css/local.css.sample`을 넣어두었습니다. (local.css.sample을 local.css로 카피하면 기본 로고가 보이게 됩니다.)

---

1번. navbar fixed는 기본 부트스트랩에서 지원합니다만, 현재 사이드 구현 방식이 부트스트랩 방식으로 한 것이 아닙니다.

1) 부트스트랩 방식을 사용한다면 http://www.bootply.com/90936 에서 나온 방식
2) jQuery를 사용하면 http://andrewhenderson.me/wp-content/tutorials/jquery-sticky-content/index.html 방식도 가능할 것입니다.

2)번 jQuery 방식을 쓰는 것이 현재 적절할 것으로 생각되는데,
위의 2번 링크에 나온 방식을 적용해 본다면 다음 코드를 `js/local.js` 에 넣어주시면 됩니다.

`js/local.js`에 넣은 자바스크립트는 문서 로딩이 완료된 이후에 실행됩니다. (즉 jquery의 `$(function() { ... });`에 의해)

```
if (!!$('.rssChanges').offset()) { // make sure this element exists
    var stickyTop = $('.rssChanges').offset().top;
    $(window).scroll(function(){ // scroll event
        var windowTop = $(window).scrollTop(); // returns number

        if (stickyTop < windowTop){
            $('.rssChanges').css({ position: 'fixed', top: 0 });
        } else {
            $('.rssChanges').css('position','static');
        }
    });
}

```

다만, 이 경우 모바일에서는 의도대로 작동하지 않으니 참고만 하시기 바랍니다.

**Comment by wkpark** [comment]
로고 관련 수정만 했으며, 우측메뉴 고정 지원은 보류합니다.

**Comment by NbverHub** [comment]
로고대신 paper 처럼 sitename을 그냥 표시하게 할 수는 없나요? 로고가 없는 사이트도 있을터이니..

**Comment by wkpark** [comment]
```
.navbar-brand span {
  display:none;
}
```

라는 부분이 `css/compat.css`에 들어있습니다.

이 경우 `css/local.css`에 다음을 추가하면 텍스트가 보이게 될 것으로 생각되네요.

```
.navbar-brand span {
  display:inline-block;
}
```

**Comment by NbverHub** [comment]
이제 잘 되네요.

**Comment by wkpark** [comment]
로고 부분만 수정하고 이 이슈는 닫겠습니다~
